# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

# Departing from the implicit _user.c scheme
XDP_TARGETS  := xdp_prog_kern
XDP_TARGETS  += xdp_prog_kern_light
USER_TARGETS := xdp_loader
USER_TARGETS += xdp_loader_light

LIBBPF_DIR = ../../libbpf/src/
COMMON_DIR = ../common/

include $(COMMON_DIR)/common.mk

