#!/bin/sh
#
# dtnmenu - scripts launched for dtntune to provide a menu of 
# routine administrative tasks
#

# when viewing this script, set tabstops to 4

# main execution thread
sh dtn_menu.sh
exit 0

